export const HABITS = [
  "Berdiri setiap 30–45 menit",
  "HP sejajar mata saat digunakan",
  "Bahu tidak membungkuk ke depan",
  "Duduk dengan tulang belakang netral",
  "Tidak menunduk dalam waktu lama",
];

export const RATINGS = ['😴', '😣', '😐', '😊', '💪'];
export const RATING_LABELS = ['Sangat Lelah', 'Kurang Enak', 'Biasa', 'Baik', 'Luar Biasa!'];

export type Exercise = { name: string; sets: number; detail: string };
export type WeekData = { week: number; title: string; focus: string; section1: Exercise[]; section2: Exercise[] };

export const WEEKS: WeekData[] = [
  { week: 1, title: "Minggu 1", focus: "Membangun kesadaran postur", section1: [{ name: "Chin Tuck", sets: 2, detail: "10 repetisi" }, { name: "Thoracic Extension", sets: 2, detail: "10 repetisi" }, { name: "Shoulder Squeeze", sets: 2, detail: "10 repetisi" }, { name: "Pec Stretch", sets: 2, detail: "20 dtk" }], section2: [{ name: "Band Row", sets: 3, detail: "10 rep" }, { name: "Wall Slide", sets: 2, detail: "8 rep" }, { name: "Dead Bug", sets: 2, detail: "8 rep" }, { name: "Bird Dog", sets: 2, detail: "6 rep" }, { name: "Glute Bridge", sets: 2, detail: "12 rep" }, { name: "Side Plank", sets: 2, detail: "15 dtk" }] },
  { week: 2, title: "Minggu 2", focus: "Adaptasi gerakan", section1: [{ name: "Chin Tuck", sets: 3, detail: "10 repetisi" }, { name: "Thoracic Extension", sets: 2, detail: "12 repetisi" }, { name: "Shoulder Squeeze", sets: 3, detail: "10 repetisi" }, { name: "Pec Stretch", sets: 2, detail: "25 dtk" }], section2: [{ name: "Band Row", sets: 3, detail: "12 rep" }, { name: "Wall Slide", sets: 3, detail: "10 rep" }, { name: "Dead Bug", sets: 3, detail: "8 rep" }, { name: "Bird Dog", sets: 3, detail: "6 rep" }, { name: "Glute Bridge", sets: 3, detail: "12 rep" }, { name: "Side Plank", sets: 2, detail: "20 dtk" }] },
  { week: 3, title: "Minggu 3", focus: "Meningkatkan volume", section1: [{ name: "Chin Tuck", sets: 3, detail: "12 repetisi" }, { name: "Thoracic Extension", sets: 3, detail: "10 repetisi" }, { name: "Shoulder Squeeze", sets: 3, detail: "12 repetisi" }, { name: "Pec Stretch", sets: 2, detail: "30 dtk" }], section2: [{ name: "Band Row", sets: 3, detail: "12 rep" }, { name: "Wall Slide", sets: 3, detail: "10 rep" }, { name: "Dead Bug", sets: 3, detail: "10 rep" }, { name: "Bird Dog", sets: 3, detail: "8 rep" }, { name: "Glute Bridge", sets: 3, detail: "15 rep" }, { name: "Side Plank", sets: 3, detail: "20 dtk" }] },
  { week: 4, title: "Minggu 4", focus: "Kontrol motor", section1: [{ name: "Chin Tuck", sets: 3, detail: "12 repetisi" }, { name: "Thoracic Extension", sets: 3, detail: "12 repetisi" }, { name: "Shoulder Squeeze", sets: 3, detail: "15 repetisi" }, { name: "Pec Stretch", sets: 3, detail: "30 dtk" }], section2: [{ name: "Band Row", sets: 4, detail: "12 rep" }, { name: "Wall Slide", sets: 3, detail: "12 rep" }, { name: "Dead Bug", sets: 3, detail: "10 rep" }, { name: "Bird Dog", sets: 3, detail: "10 rep" }, { name: "Glute Bridge", sets: 3, detail: "15 rep" }, { name: "Side Plank", sets: 3, detail: "25 dtk" }] },
  { week: 5, title: "Minggu 5", focus: "Kekuatan fungsional", section1: [{ name: "Chin Tuck", sets: 3, detail: "15 repetisi" }, { name: "Thoracic Extension", sets: 3, detail: "12 repetisi" }, { name: "Shoulder Squeeze", sets: 3, detail: "15 repetisi" }, { name: "Pec Stretch", sets: 3, detail: "30 dtk" }], section2: [{ name: "Band Row", sets: 4, detail: "12 rep" }, { name: "Wall Slide", sets: 3, detail: "12 rep" }, { name: "Dead Bug", sets: 3, detail: "12 rep" }, { name: "Bird Dog", sets: 3, detail: "10 rep" }, { name: "Glute Bridge", sets: 3, detail: "20 rep" }, { name: "Side Plank", sets: 3, detail: "30 dtk" }] },
  { week: 6, title: "Minggu 6", focus: "Otomatisasi postur", section1: [{ name: "Chin Tuck", sets: 3, detail: "15 repetisi" }, { name: "Thoracic Extension", sets: 3, detail: "15 repetisi" }, { name: "Shoulder Squeeze", sets: 3, detail: "15 repetisi" }, { name: "Pec Stretch", sets: 3, detail: "35 dtk" }], section2: [{ name: "Band Row", sets: 4, detail: "15 rep" }, { name: "Wall Slide", sets: 4, detail: "12 rep" }, { name: "Dead Bug", sets: 4, detail: "10 rep" }, { name: "Bird Dog", sets: 3, detail: "12 rep" }, { name: "Glute Bridge", sets: 3, detail: "20 rep" }, { name: "Side Plank", sets: 3, detail: "35 dtk" }] },
  { week: 7, title: "Minggu 7", focus: "Stamina postur", section1: [{ name: "Chin Tuck", sets: 3, detail: "15 repetisi" }, { name: "Thoracic Extension", sets: 3, detail: "15 repetisi" }, { name: "Shoulder Squeeze", sets: 4, detail: "15 repetisi" }, { name: "Pec Stretch", sets: 3, detail: "40 dtk" }], section2: [{ name: "Band Row", sets: 4, detail: "15 rep" }, { name: "Wall Slide", sets: 4, detail: "12 rep" }, { name: "Dead Bug", sets: 4, detail: "12 rep" }, { name: "Bird Dog", sets: 4, detail: "10 rep" }, { name: "Glute Bridge", sets: 4, detail: "20 rep" }, { name: "Side Plank", sets: 3, detail: "40 dtk" }] },
  { week: 8, title: "Minggu 8", focus: "Kebiasaan permanen", section1: [{ name: "Chin Tuck", sets: 3, detail: "15 repetisi" }, { name: "Thoracic Extension", sets: 3, detail: "15 repetisi" }, { name: "Shoulder Squeeze", sets: 4, detail: "15 repetisi" }, { name: "Pec Stretch", sets: 3, detail: "45 dtk" }], section2: [{ name: "Band Row", sets: 4, detail: "15 rep" }, { name: "Wall Slide", sets: 4, detail: "15 rep" }, { name: "Dead Bug", sets: 4, detail: "12 rep" }, { name: "Bird Dog", sets: 4, detail: "12 rep" }, { name: "Glute Bridge", sets: 4, detail: "20 rep" }, { name: "Side Plank", sets: 4, detail: "40 dtk" }] },
];
